### ISSUE TITLE
API Version V1

### ISSUE THREAD

**Issue by mnibecker** [juttle/juttle-client-library#1]
Here's my thoughts on how the api should work out the gate. Below is a more complex usage of the library - running a program that has inputs. We'll first want to render the inputs and give the user a chance to selected values. With our inputs values in hand, we'll go ahead and run the program:

```
let client = new require('Juttle')('http://localhost:9000');
let view = new client.View(document.getElementById('view'));
let inputs;

let bundle = {
   program: "input name: text; emit | put name=name;",
   modules: []
}

client.describe(bundle)
.then((progInfo) => {
    if (progInfo.inputs.length > 0) {
        inputs = new client.Input(document.getElementById('inputs'));
        return inputs.render(bundle);
    }
})

function onRunClick() {
    view.run({
        bundle,
        values: inputs
    });
}

document.getElementById('btn-run').addEventListener('click', onRunClick);
```
Lets break it down:

First we instantiate a new Juttle object by passing through a url pointing to a juttled instance.

The resulting client obj has three properties:

### `describe(bundle)`  

A function returning a promise that describes a bundle (or program). It will include inputs (if any) and views for the program.

_What's a bundle?_ A bundle is a resolved juttle program. It looks like this: `{ program: "emit", modules: []}` 

### `Input(DOMelement)`

A class for rendering a program's inputs on a given DOM Element. It has two methods:

`render(bundle)` - Returns a promise. Fetches the inputs from juttled and renders them.

`getValues()` - Returns a list of the inputs with their selected values.

### `View(DOMelement)`

A class for rendering the output of a bundle. Keeping it simple, this class has one method `run(bundle, inputValues)`. Render returns a promise that resolves when the program has successfully started.

**Comment by mnibecker** [comment]
@davidvgalbraith here you go, would love your thoughts.
fyi @mccanne

**Comment by davidvgalbraith** [comment]
At what point does the user get to fill in the inputs? It looks like we skip to `view.render` immediately after `inputs.render` finishes.

**Comment by mnibecker** [comment]
Very true, I suppose to make this more real life I could add a `$(.btn-el).click();` handler that would render the view.

**Comment by mnibecker** [comment]
@davidvgalbraith updated taken into account your comments
