### ISSUE TITLE
Create Readme

### ISSUE THREAD

**Issue by mnibecker** [juttle/juttle-client-library#3]
It would be nice to have a readme that would cover the ground of:

1. How the heck do I use this thing
2. How can I contribute

**Comment by dmehra** [comment]
For contributing there will be CONTRiBUTING.md in juttle repo, you can just point to that.

**Comment by jadbox** [comment]
+ api docs or/and a few simple examples would be good too

Offhand, not sure how this relates to Juttle-viz without the readme.
